### ISSUE TITLE
Use maintenance/run.php

### ISSUE THREAD

**Issue by MaMaKow** [gpunktschmitz/mediawiki-updater#3]
Hi!

I just tested your script. And it still works for me.
There was however a deprecation warning:

*******************************************************************************
NOTE: Do not run maintenance scripts directly, use maintenance/run.php instead!
      Running scripts directly has been deprecated in MediaWiki 1.40.
      It may not work for some (or any) scripts in the future.
*******************************************************************************

In order to correct the script only one line has to be changed:

 #execute update script
244 ${PHPEXECUTABLE} ${MEDIAWIKIDIR}/maintenance/run.php update.php

Thank you very much for sharing your script!

**Comment by gpunktschmitz** [comment]
thanks @MaMaKow! I've updated the script with you change suggestion.
